/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ModelsSlugRouteImport } from './routes/models.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finder': typeof FinderRoute
  '/methodology': typeof MethodologyRoute
  '/models/$slug': typeof ModelsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finder': typeof FinderRoute
  '/methodology': typeof MethodologyRoute
  '/models/$slug': typeof ModelsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finder': typeof FinderRoute
  '/methodology': typeof MethodologyRoute
  '/models/$slug': typeof ModelsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/finder' | '/methodology' | '/models/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/finder' | '/methodology' | '/models/$slug'
  id: '__root__' | '/' | '/finder' | '/methodology' | '/models/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinderRoute: typeof FinderRoute
  MethodologyRoute: typeof MethodologyRoute
  ModelsSlugRoute: typeof ModelsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinderRoute: FinderRoute,
  MethodologyRoute: MethodologyRoute,
  ModelsSlugRoute: ModelsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
